name: Test GitHub Packages
on: [workflow_dispatch,push]
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  SOURCE_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  REPOSITORY_URL: https://github.com/${{ github.repository }}
jobs:
  # ===================================================================================================================
  # Publish Job
  # ===================================================================================================================
  publish:
    name: Publish Packages @ 0.0.${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # ----------------------------------------------------------------------- Setup Tools
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          source-url: ${{ env.SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

      # ----------------------------------------------------------------------- Build Packages
      - name: Build Packages
        run: dotnet pack /p:CiVersion=0.0.${{ github.run_number }} /p:RepositoryUrl=${{ env.REPOSITORY_URL }}

      - name: List built packages
        run: ls packages/

      # ----------------------------------------------------------------------- Push Packages
      - name: Push Packages
        run: dotnet nuget push "*.nupkg" --source=${{ env.SOURCE_URL }}
        working-directory: packages
        env:
          # This is a workaround for https://github.com/NuGet/Home/issues/9775
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
          NUGET_AUTH_TOKEN: ${{ github.token }}

  # ===================================================================================================================
  # Restore Job
  # ===================================================================================================================
  restore:
    name: Restore ${{ matrix.package }} @ 0.0.${{ github.run_number }}${{ matrix.version-suffix }}
    needs: publish
    strategy:
      fail-fast: false
      matrix:
        package: [PackageWithoutBuildMetadata, PackageWithBuildMetadata]
        version-suffix: ['', '+BuildMetadata']
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      # (We need to checkout for the make-nuget-config.py script)
      - name: Checkout
        uses: actions/checkout@v2

      # ----------------------------------------------------------------------- Setup Tools
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          source-url: ${{ env.SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      
      # ----------------------------------------------------------------------- Create Project
      - name: Create Project
        run: dotnet new console

      # ----------------------------------------------------------------------- Install Package
      - name: Install Package
        run: dotnet add package ${{ matrix.package }} --version 0.0.${{ github.run_number }}${{ matrix.version-suffix }}
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
